version: "3.6"

networks:
  default:
    external:
      name: network

volumes:
  redis-persistence:

services:
  notify-server-nodejs:
    container_name: notify-server-nodejs-alias
    build:
      context: .
      dockerfile: ./build/nodejs/Dockerfile
    restart: "always"
    image: registry.gitlab.com/aliasgame/notify:node_14
    env_file: ./build/.env.list
